sudo: required
services:
    - docker

before_install:
    - docker build -t l01c/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true l01c/react-test npm test -- --coverage

after_success:
    - docker build -t l01c/multi-client ./client
    - docker build -t l01c/multi-client ./nginx
    - docker build -t l01c/multi-client ./server
    - docker build -t l01c/multi-client ./worker

